# Generated by Django 2.2.24 on 2023-01-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLink', models.CharField(max_length=500)),
                ('wordCount', models.IntegerField()),
                ('links', models.CharField(max_length=1000)),
                ('mediaLinks', models.CharField(max_length=1000)),
                ('fav', models.BooleanField(default=False)),
            ],
        ),
    ]
