# Generated by Django 2.2.24 on 2023-01-21 08:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_count',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
