# Generated by Django 2.2.24 on 2023-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20230121_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_count',
            name='links',
            field=models.CharField(max_length=1000),
        ),
    ]
